/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reservasdepistas.gui;

import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author diego
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    
    FondoPanel fondo = new FondoPanel();
    
    Frame frame = new Frame("PantallaPrincipal");
    
    public PantallaPrincipal() {
        
        this.setContentPane(fondo);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNuevaReservaP = new javax.swing.JButton();
        btSalirP = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuReservas = new javax.swing.JMenu();
        MenuItemNuevaReserva = new javax.swing.JRadioButtonMenuItem();
        menuSalir = new javax.swing.JMenu();
        MenuItemSalir = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Club de Padel");
        setResizable(false);

        btNuevaReservaP.setBackground(new java.awt.Color(255, 255, 153));
        btNuevaReservaP.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 30)); // NOI18N
        btNuevaReservaP.setForeground(new java.awt.Color(0, 0, 204));
        btNuevaReservaP.setText("Nueva reserva");
        btNuevaReservaP.setToolTipText("Para generar una nueva reserva");
        btNuevaReservaP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btNuevaReservaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevaReservaPActionPerformed(evt);
            }
        });

        btSalirP.setBackground(new java.awt.Color(255, 255, 153));
        btSalirP.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        btSalirP.setForeground(new java.awt.Color(255, 0, 51));
        btSalirP.setText("Salir");
        btSalirP.setToolTipText("Para cerrar la aplicacion");
        btSalirP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirPActionPerformed(evt);
            }
        });

        menuReservas.setText("Reservas");
        menuReservas.setToolTipText("Para generar una nueva reserva");
        menuReservas.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N

        MenuItemNuevaReserva.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        MenuItemNuevaReserva.setSelected(true);
        MenuItemNuevaReserva.setText("Nueva reserva");
        MenuItemNuevaReserva.setToolTipText("Para generar una nueva reserva");
        MenuItemNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNuevaReservaActionPerformed(evt);
            }
        });
        menuReservas.add(MenuItemNuevaReserva);

        barraMenu.add(menuReservas);

        menuSalir.setText("Salir");
        menuSalir.setToolTipText("Salir de la aplicacion");
        menuSalir.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N

        MenuItemSalir.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        MenuItemSalir.setSelected(true);
        MenuItemSalir.setText("¿salir?");
        MenuItemSalir.setToolTipText("Hacer click aquí para salir de la aplicacion");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(MenuItemSalir);

        barraMenu.add(menuSalir);

        setJMenuBar(barraMenu);
        barraMenu.getAccessibleContext().setAccessibleName("barraMenu");
        barraMenu.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addComponent(btSalirP)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btNuevaReservaP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btNuevaReservaP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btSalirP)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        int option = JOptionPane.showConfirmDialog(frame, "¿Desea salir?", "Confirmación de cierre de la aplicación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(option == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void btNuevaReservaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevaReservaPActionPerformed
        DialogoReservas dialogoreservas = new DialogoReservas(this, true);
        dialogoreservas.setVisible(true);
    }//GEN-LAST:event_btNuevaReservaPActionPerformed

    private void btSalirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirPActionPerformed
        int option = JOptionPane.showConfirmDialog(frame,"¿Desea salir?", "Confirmación de cierre",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(option == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btSalirPActionPerformed

    private void MenuItemNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNuevaReservaActionPerformed
        DialogoReservas dialogoreservas = new DialogoReservas (this, true);
        dialogoreservas.setVisible(true);
    }//GEN-LAST:event_MenuItemNuevaReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem MenuItemNuevaReserva;
    private javax.swing.JRadioButtonMenuItem MenuItemSalir;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btNuevaReservaP;
    private javax.swing.JButton btSalirP;
    private javax.swing.JMenu menuReservas;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables


    public class FondoPanel extends JPanel{
        
        private Image imagen;
        
        @Override
        public void paint (Graphics g){
            
            imagen = new ImageIcon(getClass().getResource("/image/club.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
        
    }
    
}

